# Generated by Django 2.2.1 on 2019-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('topics', models.CharField(max_length=420)),
            ],
        ),
    ]
