# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.TextField(max_length=20)),
                ('message', models.TextField(null=True)),
                ('category', models.CharField(choices=[('sell', 'SELL'), ('rent', 'RENT'), ('request', 'REQUEST')], default='sell', max_length=6)),
                ('message_html', models.TextField(editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.User')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('user', 'message')]),
        ),
    ]
