# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sell', 'SELL'), ('rent', 'RENT'), ('request', 'REQUEST')], default='sell', max_length=6),
        ),
    ]
